### PR TITLE
Pr from esurio

### PR DESCRIPTION
**Pull request by esurio**
Hi, 
thank you Agis for this. Its exactly what I needed.
I had issues with Environment class - some collision on naming withing swiftui. 

I've cleared few warning about dangling pointer. Thank you so much :)

### CODE REVIEW

**Comment by agisboye** [comment]
Hi Esurio! I'm glad you find the package useful.

Thanks for this PR. I'm a little hesitant to merge it for a number of reasons:
- It seems a number of Xcode related files have been introduced. With the introduction of SPM support in Xcode, there is no need for Xcode projects any more so I would prefer to keep these files out of the repo.
- If you have any naming conflicts with `Environment`, try prefixing the type name with the name of the library: `SwiftLMDB.Environment`. You could also use a typealias in your app: `typealias LMDBEnv = SwiftLMDB.Environment`. I don't believe the conflict should be solved by renaming types in SwiftLMDB.

Good catch with the dangling pointer. In your solution, I think the issue is still there since you are creating a `UnsafeBufferPointer` in the same way I did. I've tried fixing it in c7a8631ea6e38dcf8c31e0adc8b2fd5c285a54c3.

**Comment by esurio** [comment]
hey Agisboye, 

I am just learning - so I it is doubtful whether what I did is correct. I really like LMDB approach. As for additional files - XCode auto adds to commit files and I pushed them by mistake.  Tried to mitigate that, failure is a lifestyle ;-)

Xcode was lost between this and Swiftui module. 
Probably I am not using it right. Renaming will break compatibility - so I agree. I was not able to fix it with typealias:
"SwiftLMDB has no member Environment" (i tried: var environment = SwiftLMDB.Environment).

As for dangling indices I found answer on stackoverflow, after this - warning disappeared. But my understanding of the case is limited. 

Initially I did not plan to make PR - due to renaming. But decided you might have some insight - which you did :) 
I'll test your latest commit today and write to you :) 

Have a good one! 
Karol

**Comment by esurio** [comment]
I've tested. Unfortunately - problem persist with name collision. 

As for dangling indices your solution is much better :) 
I'll leave PR open in case you had time to answer regarding this type alias. 
My code snippet: https://github.com/esurio/SwiftLMDB

And I'll close it tomorrow if not :) 
Once again thank you for your fantastic work!

**Comment by agisboye** [comment]
We're all learning. :-)

It should always be possible to resolve naming collisions by prefixing the type with the name of the module. So if you want `Environment` from SwiftLMDB, you can refer to it as `SwiftLMDB.Environment`. Same thing goes for SwiftUI.

The error you're getting is because you've used `var environemnt = ...`. Use the `typealias` keyword instead.

**Comment by esurio** [comment]
typealias did not help. However i was revisiting this part of code in hope i am smarter now. Figures - I am! 
It was class naming conflict with swiftUi.
here is bug description too:
https://forums.swift.org/t/frameworkname-is-not-a-member-type-of-frameworkname-errors-inside-swiftinterface/28962

import Combine
//import SwiftUI
import SwiftLMDB
import FileProvider

class CreatorViewModel: ObservableObject {


this enabled me to use SwiftLMDB as is. Great. :)

**Comment by agisboye** [comment]
That's great! Let me know if you run into any more issues. :-)

**Pull request closed without merging**
